defmodule Mix.Tasks.Arbiter.ThirdPartyNotices do
  @shortdoc "Regenerate THIRD_PARTY_NOTICES.md from local dependency metadata"
  @moduledoc """
  Regenerates the root `THIRD_PARTY_NOTICES.md` by walking `mix.lock` and
  reading each dependency's license out of local, already-fetched metadata —
  `deps/<name>/hex_metadata.config` for Hex packages, falling back to the
  dep's own `mix.exs` `package[:licenses]`. It makes no network calls and
  does not shell out to `mix hex.info`.

  ## Usage

      mix arbiter.third_party_notices

  Exits non-zero, naming the offending package, if any dependency's license
  cannot be determined from local metadata.
  """

  use Mix.Task

  @relpath "THIRD_PARTY_NOTICES.md"

  # heroicons is fetched via a sparse `github:` dep (`app: false, compile:
  # false`) used only to embed SVG markup into CoreComponents at compile
  # time. It never fetches a mix.exs or hex_metadata.config, so its license
  # can't be read the way every Hex package's can. Its upstream LICENSE
  # (https://github.com/tailwindlabs/heroicons/blob/master/LICENSE) is MIT;
  # recorded here as a static fact, not fetched over the network.
  @non_hex_licenses %{"heroicons" => ["MIT"]}

  # A handful of Hex packages carry their license in `hex_metadata.config`
  # as a human-readable name rather than the SPDX identifier THIRD_PARTY_NOTICES.md
  # is meant to record (AC #3). Normalize the ones this dependency tree
  # actually has rather than guess at a general free-text-to-SPDX mapping.
  @spdx_aliases %{
    "Apache 2.0" => "Apache-2.0",
    "BSD 2-Clause" => "BSD-2-Clause"
  }

  @impl Mix.Task
  def run(_argv) do
    path = Path.join(root_path(), @relpath)
    File.write!(path, generate())
    Mix.shell().info("Wrote #{@relpath}")
  end

  @doc false
  def generate(root \\ root_path()) do
    root
    |> Path.join("mix.lock")
    |> Mix.Dep.Lock.read()
    |> Enum.sort_by(fn {name, _spec} -> Atom.to_string(name) end)
    |> Enum.map(fn {name, spec} -> entry(name, spec, root) end)
    |> render()
  end

  @doc false
  def licenses_for(name, root) when is_binary(name) do
    hex_metadata_path = Path.join([root, "deps", name, "hex_metadata.config"])
    mix_exs_path = Path.join([root, "deps", name, "mix.exs"])

    cond do
      File.exists?(hex_metadata_path) ->
        licenses_from_hex_metadata!(hex_metadata_path, name)

      File.exists?(mix_exs_path) ->
        licenses_from_mix_exs!(mix_exs_path, name)

      Map.has_key?(@non_hex_licenses, name) ->
        Map.fetch!(@non_hex_licenses, name)

      true ->
        Mix.raise(
          "Cannot determine license for dependency #{name}: no hex_metadata.config, " <>
            "mix.exs, or recorded override found under #{root}/deps/#{name}"
        )
    end
  end

  defp entry(name, spec, root) do
    name_str = Atom.to_string(name)
    licenses = name_str |> licenses_for(root) |> Enum.map(&normalize_spdx/1)
    {name_str, version_of(spec), licenses}
  end

  defp normalize_spdx(license), do: Map.get(@spdx_aliases, license, license)

  defp version_of({:hex, _app, version, _checksum, _managers, _deps, _repo, _outer}), do: version
  defp version_of({:git, _url, ref, _opts}), do: String.slice(ref, 0, 7)

  defp licenses_from_hex_metadata!(path, name) do
    case :file.consult(String.to_charlist(path)) do
      {:ok, terms} ->
        terms
        |> Enum.find_value(fn
          {"licenses", licenses} -> licenses
          _ -> nil
        end)
        |> case do
          licenses when is_list(licenses) and licenses != [] ->
            licenses

          _ ->
            Mix.raise("Dependency #{name} has no licenses field in hex_metadata.config")
        end

      {:error, reason} ->
        Mix.raise("Cannot read hex_metadata.config for #{name}: #{inspect(reason)}")
    end
  end

  defp licenses_from_mix_exs!(path, name) do
    content = File.read!(path)

    case Regex.run(~r/licenses:\s*\[([^\]]*)\]/, content) do
      [_, list] ->
        list
        |> String.split(",")
        |> Enum.map(&(&1 |> String.trim() |> String.trim("\"")))
        |> Enum.reject(&(&1 == ""))

      nil ->
        Mix.raise("Dependency #{name}'s mix.exs has no package[:licenses] entry")
    end
  end

  defp render(entries) do
    header = """
    # Third-Party Notices

    Arbiter is built on the open-source packages listed below, resolved from
    `mix.lock`. This file is generated by `mix arbiter.third_party_notices` —
    do not edit it by hand.

    | Package | Version | License(s) |
    | --- | --- | --- |
    """

    rows =
      Enum.map_join(entries, "", fn {name, version, licenses} ->
        "| #{name} | #{version} | #{Enum.join(licenses, ", ")} |\n"
      end)

    header <> rows
  end

  defp root_path do
    Mix.Project.deps_path() |> Path.dirname()
  end
end
