defmodule Arbiter.Beads do
  @moduledoc """
  Ash domain for the bead ledger.

  Holds workspaces, issues, dependencies, convoys, and audit events. This module
  is the entry point for code that creates / reads / updates beads — call
  through `Ash` (e.g. `Ash.create(Arbiter.Beads.Workspace, attrs)`).

  Resources land here as they're built across the gte-* beads:

    * `Arbiter.Beads.Workspace` — gte-P1 (this bead) — workspace with config JSON
      (vernacular + tracker config). Default workspace ships gas-town vocab + `:none`
      tracker.
    * `Arbiter.Beads.Issue` — gte-002 — Ash issue resource with status FSM, audit
      via paper_trail, tracker_type/tracker_ref fields.
    * `Arbiter.Beads.Dependency` — gte-003 — bead-to-bead edges (blocks, depends_on).
    * `Arbiter.Beads.Convoy` — gte-004 — batches of beads with derived progress.
  """

  use Ash.Domain

  resources do
    resource(Arbiter.Settings)
    resource(Arbiter.Beads.Workspace)
    resource(Arbiter.Beads.Issue)
    # Auto-generated by AshPaperTrail for Issue. Tracks every create/update with
    # diff + actor; queryable via Arbiter.Beads.Issue.Version.
    resource(Arbiter.Beads.Issue.Version)
    resource(Arbiter.Beads.Convoy)
    resource(Arbiter.Beads.ConvoyMembership)
    resource(Arbiter.Beads.Dependency)
  end
end
