defmodule Arbiter.Tasks do
  @moduledoc """
  Ash domain for the task ledger.

  Holds workspaces, issues, dependencies, and audit events. This module
  is the entry point for code that creates / reads / updates tasks — call
  through `Ash` (e.g. `Ash.create(Arbiter.Tasks.Workspace, attrs)`).

  Resources land here as they're built across the gte-* tasks:

    * `Arbiter.Tasks.Workspace` — gte-P1 (this task) — workspace with config JSON
      (tracker config). Default workspace ships a `:none` tracker.
    * `Arbiter.Tasks.Issue` — gte-002 — Ash issue resource with status FSM, audit
      via paper_trail, tracker_type/tracker_ref fields. A task can be a *parent*
      of other tasks via `:parent_of` dependency edges; it then rolls up
      `{child_closed, child_total}` progress and optionally auto-closes when all
      its children are done (the `auto_close` flag).
    * `Arbiter.Tasks.Dependency` — gte-003 — task-to-task edges (blocks, depends_on,
      parent_of).
    * `Arbiter.Tasks.Graph` — bd-3bbgqi — execution unit grouping directives for
      coordinated execution. Orthogonal to epics. Run states: draft|running|paused|drained.
    * `Arbiter.Tasks.GraphMember` — bd-3bbgqi — join resource linking a Graph to its
      member Issues (directives). Reuses Dependency edges for ordering.
  """

  use Ash.Domain

  resources do
    resource Arbiter.Tasks.Workspace
    resource Arbiter.Tasks.Issue
    # Auto-generated by AshPaperTrail for Issue. Tracks every create/update with
    # diff + actor; queryable via Arbiter.Tasks.Issue.Version.
    resource Arbiter.Tasks.Issue.Version
    resource Arbiter.Tasks.Dependency
    resource Arbiter.Tasks.Graph
    resource Arbiter.Tasks.GraphMember
  end
end
