defmodule Arbiter.Repo.Migrations.AddIssueResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add :prefix, :text, null: false, default: "bd"
    end

    create table(:issues_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_action_inputs, :map, null: false
      add :version_source_id, :text, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:issues, primary_key: false) do
      add :id, :text, null: false, primary_key: true
    end

    alter table(:issues_versions) do
      modify :version_source_id,
             references(:issues,
               column: :id,
               name: "issues_versions_version_source_id_fkey",
               type: :text,
               prefix: "public"
             )
    end

    alter table(:issues) do
      add :title, :text, null: false
      add :description, :text, default: ""
      add :acceptance, :text, default: ""
      add :notes, :text, default: ""
      add :qa_notes, :text, default: ""
      add :deployment_notes, :text, default: ""
      add :status, :text, null: false, default: "open"
      add :priority, :bigint, null: false, default: 2
      add :issue_type, :text, null: false, default: "task"
      add :assignee, :text
      add :tracker_type, :text, null: false, default: "none"
      add :tracker_ref, :text
      add :closed_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "issues_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end
  end

  def down do
    drop constraint(:issues, "issues_workspace_id_fkey")

    alter table(:issues) do
      remove :workspace_id
      remove :updated_at
      remove :created_at
      remove :closed_at
      remove :tracker_ref
      remove :tracker_type
      remove :assignee
      remove :issue_type
      remove :priority
      remove :status
      remove :deployment_notes
      remove :qa_notes
      remove :notes
      remove :acceptance
      remove :description
      remove :title
    end

    drop constraint(:issues_versions, "issues_versions_version_source_id_fkey")

    alter table(:issues_versions) do
      modify :version_source_id, :text
    end

    drop table(:issues)

    drop table(:issues_versions)

    alter table(:workspaces) do
      remove :prefix
    end
  end
end
