defmodule Arbiter.Repo.Migrations.AddBrandingToSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:global_settings) do
      add :branding, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:global_settings) do
      remove :branding
    end
  end
end
