defmodule Arbiter.Repo.Migrations.AddRepoToGraphMembers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:graph_members) do
      add(:repo, :text)
    end
  end

  def down do
    alter table(:graph_members) do
      remove(:repo)
    end
  end
end
