defmodule Arbiter.Repo.Migrations.AddMessagesResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :from_ref, :text
      add :to_ref, :text
      add :workspace_id, :text, null: false
      add :subject, :text
      add :body, :text, null: false, default: ""
      add :read_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:messages, [:workspace_id, :to_ref, :read_at])
  end

  def down do
    drop_if_exists index(:messages, [:workspace_id, :to_ref, :read_at])

    drop table(:messages)
  end
end
