defmodule Arbiter.Repo.Migrations.AddMrRefToWorkerRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:worker_runs) do
      add(:mr_ref, :text)
      add(:merger_url, :text)
    end
  end

  def down do
    alter table(:worker_runs) do
      remove(:merger_url)
      remove(:mr_ref)
    end
  end
end
