defmodule Arbiter.Repo.Migrations.AddPolecatRunsResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # NOTE: workflow_machine_states already exists from
    # 20260520144412_create_workflow_machine_states.exs (hand-written, no
    # snapshot was committed at the time). The generator therefore emits a
    # spurious `create table` for it here; we strip that block but keep the
    # new snapshot under priv/resource_snapshots so future generations stay
    # clean.
    create table(:polecat_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bead_id, :text, null: false
      add :bead_title, :text
      add :rig, :text, null: false
      add :workspace_id, :text
      add :status, :text, null: false, default: "running"
      add :started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :exit_code, :bigint
      add :output_lines, {:array, :text}, default: []
      add :failure_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:polecat_runs, [:workspace_id, :status, :started_at])
  end

  def down do
    drop_if_exists index(:polecat_runs, [:workspace_id, :status, :started_at])

    drop table(:polecat_runs)
  end
end
