defmodule Arbiter.Repo.Migrations.AddConvoyResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:convoys, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :title, :text, null: false
      add :status, :text, null: false, default: "open"
      add :lifecycle, :text, null: false, default: "system_managed"
      add :closed_at, :utc_datetime_usec
      add :closed_reason, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "convoys_workspace_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create table(:convoy_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :convoy_id,
          references(:convoys,
            column: :id,
            name: "convoy_memberships_convoy_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :issue_id,
          references(:issues,
            column: :id,
            name: "convoy_memberships_issue_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:convoy_memberships, [:convoy_id, :issue_id],
             name: "convoy_memberships_convoy_issue_unique_index"
           )
  end

  def down do
    drop constraint(:convoy_memberships, "convoy_memberships_convoy_id_fkey")

    drop constraint(:convoy_memberships, "convoy_memberships_issue_id_fkey")

    drop_if_exists unique_index(:convoy_memberships, [:convoy_id, :issue_id],
                     name: "convoy_memberships_convoy_issue_unique_index"
                   )

    drop table(:convoy_memberships)

    drop constraint(:convoys, "convoys_workspace_id_fkey")

    drop table(:convoys)
  end
end
