defmodule Arbiter.Repo.Migrations.AddDifficultyToIssues do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:issues) do
      add :difficulty, :bigint
    end
  end

  def down do
    alter table(:issues) do
      remove :difficulty
    end
  end
end
