defmodule Arbiter.Repo.Migrations.AddMessageDirectiveRef do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :directive_ref, :text
    end
  end

  def down do
    alter table(:messages) do
      remove :directive_ref
    end
  end
end
