defmodule Arbiter.Repo.Migrations.AddTargetBranchToIssues do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:issues) do
      add :target_branch, :text
    end
  end

  def down do
    alter table(:issues) do
      remove :target_branch
    end
  end
end
