defmodule Arbiter.Repo.Migrations.AddEventsOccurredAtIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:events, ["occurred_at"])
  end

  def down do
    drop_if_exists index(:events, ["occurred_at"], name: "events_occurred_at_index")
  end
end
