defmodule Arbiter.Repo.Migrations.AddPrBodyToIssues do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:issues) do
      add(:pr_body, :text)
    end
  end

  def down do
    alter table(:issues) do
      remove(:pr_body)
    end
  end
end