defmodule Arbiter.Repo.Migrations.CreateEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :payload, :map, null: false, default: %{}
      add :topic, :text, null: false
      add :workspace_id, :text, null: false
      add :seq, :bigserial, null: false, primary_key: true
    end

    create index(:events, ["workspace_id", "seq"])
  end

  def down do
    drop_if_exists index(:events, ["workspace_id", "seq"], name: "events_workspace_id_seq_index")

    drop table(:events)
  end
end
