defmodule Arbiter.Repo.Migrations.AddResumedFromRunIdToPolecatRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:polecat_runs) do
      add :resumed_from_run_id, :uuid
    end
  end

  def down do
    alter table(:polecat_runs) do
      remove :resumed_from_run_id
    end
  end
end
