defmodule Arbiter.Repo.Migrations.AddPrRefToIssues do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:issues) do
      add :pr_ref, :text
    end
  end

  def down do
    alter table(:issues) do
      remove :pr_ref
    end
  end
end
