defmodule Arbiter.Repo.Migrations.InitialSqlite do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :config, :map, default: %{}
      add :prefix, :text, null: false
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:workflow_machine_states, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :error_reason, :text
      add :state, :map, null: false, default: %{}
      add :completed_steps, {:array, :text}, null: false, default: []
      add :status, :text, null: false
      add :current_step, :text, null: false
      add :vars, :map, default: %{}
      add :bead_id, :text, null: false
      add :workflow_module, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:usage_events, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :raw, :map
      add :occurred_at, :utc_datetime_usec, null: false
      add :session_id, :text
      add :polecat_run_id, :uuid
      add :exit_status, :bigint
      add :duration_ms, :bigint
      add :cost_usd, :float
      add :cache_read_tokens, :bigint
      add :cache_creation_tokens, :bigint
      add :tokens_out, :bigint
      add :tokens_in, :bigint
      add :provider, :text
      add :model, :text
      add :step, :text, null: false
      add :rig, :text
      add :workspace_id, :text
      add :bead_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:usage_events, ["bead_id", "occurred_at"])

    create index(:usage_events, ["workspace_id", "occurred_at"])

    create table(:polecat_runs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :resumed_from_run_id, :uuid
      add :failure_reason, :text
      add :output_lines, {:array, :text}, default: []
      add :exit_code, :bigint
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :workspace_id, :text
      add :rig, :text, null: false
      add :bead_title, :text
      add :bead_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:polecat_runs, ["workspace_id", "status", "started_at"])

    create table(:messages, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :read_at, :utc_datetime_usec
      add :body, :text, null: false
      add :directive_ref, :text
      add :subject, :text
      add :workspace_id, :text, null: false
      add :to_ref, :text
      add :from_ref, :text
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:messages, ["workspace_id", "to_ref", "read_at"])

    create table(:issues_versions, primary_key: false) do
      add :version_updated_at, :utc_datetime_usec, null: false
      add :version_inserted_at, :utc_datetime_usec, null: false
      add :changes, :map

      add :version_source_id,
          references(:issues,
            column: :id,
            name: "issues_versions_version_source_id_fkey",
            type: :text
          ), null: false

      add :version_action_inputs, :map, null: false
      add :version_action_name, :text, null: false
      add :version_action_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:issues, primary_key: false) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "issues_workspace_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :closed_at, :utc_datetime_usec
      add :target_branch, :text
      add :pr_ref, :text
      add :tracker_ref, :text
      add :tracker_type, :text, null: false
      add :assignee, :text
      add :issue_type, :text, null: false
      add :difficulty, :bigint
      add :priority, :bigint, null: false
      add :status, :text, null: false
      add :deployment_notes, :text
      add :qa_notes, :text
      add :notes, :text
      add :acceptance, :text
      add :description, :text
      add :title, :text, null: false
      add :id, :text, null: false, primary_key: true
    end

    create table(:global_settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :branding, :map, null: false, default: %{}
      add :vernacular, :map, null: false, default: %{}
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:dependencies, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :notes, :text
      add :created_by, :text
      add :type, :text, null: false

      add :to_issue_id,
          references(:issues,
            column: :id,
            name: "dependencies_to_issue_id_fkey",
            type: :text,
            on_delete: :restrict
          ), null: false

      add :from_issue_id,
          references(:issues,
            column: :id,
            name: "dependencies_from_issue_id_fkey",
            type: :text,
            on_delete: :restrict
          ), null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:dependencies, [:from_issue_id, :to_issue_id, :type],
             name: "dependencies_unique_edge_index"
           )

    create table(:convoys, primary_key: false) do
      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "convoys_workspace_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :closed_reason, :text
      add :closed_at, :utc_datetime_usec
      add :lifecycle, :text, null: false
      add :status, :text, null: false
      add :title, :text, null: false
      add :id, :text, null: false, primary_key: true
    end

    create table(:convoy_memberships, primary_key: false) do
      add :issue_id,
          references(:issues,
            column: :id,
            name: "convoy_memberships_issue_id_fkey",
            type: :text,
            on_delete: :delete_all
          ), null: false

      add :convoy_id,
          references(:convoys,
            column: :id,
            name: "convoy_memberships_convoy_id_fkey",
            type: :text,
            on_delete: :delete_all
          ), null: false

      add :created_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:convoy_memberships, [:convoy_id, :issue_id],
             name: "convoy_memberships_convoy_issue_unique_index"
           )
  end

  def down do
    drop_if_exists unique_index(:convoy_memberships, [:convoy_id, :issue_id],
                     name: "convoy_memberships_convoy_issue_unique_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `convoy_memberships` table without the `convoy_memberships_convoy_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `convoy_memberships` table without the `convoy_memberships_issue_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:convoy_memberships)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `convoys` table without the `convoys_workspace_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:convoys)

    drop_if_exists unique_index(:dependencies, [:from_issue_id, :to_issue_id, :type],
                     name: "dependencies_unique_edge_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `dependencies` table without the `dependencies_from_issue_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `dependencies` table without the `dependencies_to_issue_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:dependencies)

    drop table(:global_settings)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `issues` table without the `issues_workspace_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:issues)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `issues_versions` table without the `issues_versions_version_source_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:issues_versions)

    drop_if_exists index(:messages, ["workspace_id", "to_ref", "read_at"],
                     name: "messages_workspace_id_to_ref_read_at_index"
                   )

    drop table(:messages)

    drop_if_exists index(:polecat_runs, ["workspace_id", "status", "started_at"],
                     name: "polecat_runs_workspace_id_status_started_at_index"
                   )

    drop table(:polecat_runs)

    drop_if_exists index(:usage_events, ["workspace_id", "occurred_at"],
                     name: "usage_events_workspace_id_occurred_at_index"
                   )

    drop_if_exists index(:usage_events, ["bead_id", "occurred_at"],
                     name: "usage_events_bead_id_occurred_at_index"
                   )

    drop table(:usage_events)

    drop table(:workflow_machine_states)

    drop table(:workspaces)
  end
end