defmodule Arbiter.Repo.Migrations.AddUsageEventsResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:usage_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bead_id, :text, null: false
      add :workspace_id, :text
      add :rig, :text
      add :step, :text, null: false, default: "work"
      add :model, :text
      add :provider, :text
      add :tokens_in, :bigint
      add :tokens_out, :bigint
      add :cache_creation_tokens, :bigint
      add :cache_read_tokens, :bigint
      add :cost_usd, :float
      add :duration_ms, :bigint
      add :exit_status, :bigint
      add :polecat_run_id, :uuid
      add :session_id, :text
      add :occurred_at, :utc_datetime_usec, null: false
      add :raw, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:usage_events, [:bead_id, :occurred_at])

    create index(:usage_events, [:workspace_id, :occurred_at])
  end

  def down do
    drop_if_exists index(:usage_events, [:workspace_id, :occurred_at])

    drop_if_exists index(:usage_events, [:bead_id, :occurred_at])

    drop table(:usage_events)
  end
end
