defmodule Arbiter.Agents.Claude.ConfigDir do
  @moduledoc """
  An isolated `CLAUDE_CONFIG_DIR` for worker (implementer / reviewer) runs.

  ## Why

  Workers are spawned with `claude --print` inside a worktree. By default the
  child inherits the **host operator's** user-level config dir (`~/.claude`),
  which loads the operator's personal `~/.claude/CLAUDE.md`. On a developer
  install that file routinely carries personal memory — including, on this
  install, a *roleplay persona*. That persona bleeds into the worker's output:
  a REVIEWER once emitted `VERDICT: REQUEST_CHANGES` followed only by a
  theatrical flourish and **no actual findings**, stalling the gate and burning
  a full review pass. It is non-deterministic and silent (bd-3y2mda).

  The fix is to run workers against a *clean*, Arbiter-owned config dir that
  does **not** contain the operator's persona memory — so the worker's context
  is task-focused regardless of what the host operator keeps in `~/.claude`.

  ## How

  We point the spawn at a stable, Arbiter-managed directory via the
  `CLAUDE_CONFIG_DIR` env var (`Arbiter.Agents.Claude.spawn_env/1` and the
  ReviewGate's reviewer/implementer spawns both consult `env/1`). The directory is
  seeded **idempotently** on each spawn with the *minimum* a functioning worker
  needs — and nothing personal:

    * `.credentials.json` is **copied** from the operator's real config dir
      (refreshed whenever the source is newer than our copy) — never
      symlinked, since a worker refreshing its OAuth token would otherwise
      write through the link and corrupt the operator's credentials. It holds
      no persona and no permission posture.
    * `settings.json` is **generated by us** from the install-wide
      `Arbiter.Agents.SecurityPolicy.default/0` (via
      `Arbiter.Agents.Claude.Security`) — a hardened, non-empty-deny baseline.
      It is **never** symlinked from the operator's `~/.claude`, so the
      worker does **not** inherit the operator's personal permission posture
      (historically `defaultMode: auto` with an *empty* deny list). This is
      the floor; workspace-aware spawns layer the per-domain policy on top via
      `claude --settings` (bd-9u10op).
    * `CLAUDE.md` is **written by us** — a short, task-focused worker memory
      that also explicitly forbids roleplay/persona output. The operator's
      personal `CLAUDE.md` / `CLAUDE.local.md` are **never** linked, so they
      cannot load.

  Everything else the operator keeps in `~/.claude` (personal skills, agents,
  plugins, project history, …) is intentionally absent: a worker should run on
  a clean slate. The worker's own session state (history, projects) accumulates
  here, kept apart from the operator's.

  ## Worker OAuth tokens and the seeding gate (bd-6umoh9, bd-bw3466)

  Once workers hold their **own** OAuth grant, seeding them a copy of the
  operator's `.credentials.json` is actively harmful: both sides refresh the
  same refresh token and whichever goes first rotates the other out, which is
  what forced the operator to `/login` repeatedly.

  The token can be configured two ways, and `oauth_token/1` checks both — the
  spawn's workspace `worker_env` (encrypted at rest) **first**, the arbiter
  server's own process environment as the fallback (then, for a spawn with no
  workspace at all, the install-wide answer described below). bd-6umoh9 only
  checked the server environment, so on an install that configures the token
  per-workspace (the supported way) the gate never fired and seeding continued
  unchanged.

  Note the directory this gate protects is **install-wide** — one shared
  `~/.cache/arbiter/worker-claude` for every workspace. A workspace-less spawn
  (the fleet-wide `CredentialWatchdog` probe, the quota probe, a code-review
  check) runs against that same directory, so it must not copy the operator's
  credentials straight back in a second after a token-bearing spawn cleaned
  them out. The third and last source in `oauth_token/1` therefore looks
  install-wide: when *every* workspace that defines `CLAUDE_CODE_OAUTH_TOKEN`
  defines the **same** one, that is the only answer a workspace-less spawn
  could carry, so we carry it. If workspaces disagree we carry nothing rather
  than guess, and the seeding gate stands down with it.

  The load-bearing invariant is **gate fires ⟺ token injected**, per spawn:
  `seed_links/2` and `oauth_token_pairs/1` both read `oauth_token/1`, so a
  spawn is never left with neither a seeded `.credentials.json` nor a token.
  An earlier cut of bd-bw3466 broke this — the gate was asked install-wide
  while injection stayed workspace-scoped, which would have left the
  `CredentialWatchdog` probe (`Preflight.check(adapter, [])`, no workspace
  available to a fleet-wide watchdog) running against an emptied config dir
  with no token: a guaranteed 401, classified `:auth_expired`, marking the
  adapter expired and short-circuiting *every* dispatch with a false expiry
  escalation. Any future change here must keep the two in lockstep;
  `config_dir_workspace_test.exs` asserts the invariant directly.

  ## Safety / degradation

  `ensure/1` is best-effort and self-guarding. If the directory or its memory
  file can't be created it returns `:error` and the caller falls back to the
  inherited (un-isolated) config — a working-but-persona worker beats a broken
  one. A missing source credentials file is **not** fatal: the inherited
  `ANTHROPIC_API_KEY` (if any) still flows through, since we override only
  `CLAUDE_CONFIG_DIR`.

  ## Config

    * `config :arbiter, :worker_isolate_config, boolean` — master switch
      (default `true`). The test suite sets it `false` so unit tests don't touch
      the real cache dir or shell out.
    * `config :arbiter, :worker_config_dir, "/path"` — override the directory
      (tests that *do* exercise isolation point this at a tmp dir).
  """

  alias Arbiter.Agents.Claude.Security
  alias Arbiter.Agents.CredentialsRef
  alias Arbiter.Tasks.Workspace

  require Logger

  # The operator config files we link through (auth only), by name.
  # Deliberately excludes:
  #   * CLAUDE.md / CLAUDE.local.md — the persona lives there (bd-3y2mda).
  #   * settings.json — the permission posture; we *generate* a hardened one
  #     instead of inheriting the operator's (bd-9u10op). See @settings_filename.
  @seed_links ~w(.credentials.json)

  @memory_filename "CLAUDE.md"
  @settings_filename "settings.json"

  @typedoc """
  How a caller names the workspace whose `worker_env` should be consulted:
  a loaded `Workspace` struct, its id (we load it), or `nil` when the caller
  legitimately has no workspace in hand (see `oauth_token/1`).
  """
  @type workspace_source :: Workspace.t() | String.t() | nil

  @oauth_token_var "CLAUDE_CODE_OAUTH_TOKEN"

  @doc """
  The env pairs to inject into a worker spawn: `[{"CLAUDE_CONFIG_DIR", dir}]`
  when isolation is enabled and the dir is ready (`[]` otherwise — inherit the
  host config unchanged), plus `{"CLAUDE_CODE_OAUTH_TOKEN", token}` whenever a
  worker OAuth token (bd-2zigo1) is configured. All three `ConfigDir` consumers
  (`claude.ex`, `worker/claude_session.ex`,
  `workflows/code_review/checks.ex`) call this single function, so the token
  reaches every worker spawn path rather than only the ones that separately
  remember to compose it in (bd-6umoh9).

  Pass the spawn's workspace (struct or id) so a token configured the
  per-workspace way — `worker_env`, encrypted at rest — is found. The
  zero-arity form is for callers with genuinely no workspace in hand; it falls
  back to the server process environment and then to the unambiguous
  install-wide workspace token, so such a spawn is authenticated rather than
  left with neither credentials nor a token (bd-bw3466). See `oauth_token/1`
  for the precedence.
  """
  @spec env(workspace_source()) :: [{String.t(), String.t()}]
  def env(workspace \\ nil) do
    config_pairs =
      case ensure(workspace) do
        {:ok, dir} -> [{"CLAUDE_CONFIG_DIR", dir}]
        _ -> []
      end

    config_pairs ++ oauth_token_pairs(workspace)
  end

  @doc """
  Whether a worker OAuth token (`CLAUDE_CODE_OAUTH_TOKEN`, bd-2zigo1) is
  configured for this spawn. When true, workers authenticate with their
  own credential grant and must not also be seeded a copy of the operator's
  `.credentials.json` (bd-6umoh9) — sharing that file means whichever side
  refreshes first rotates the other out.
  """
  @spec oauth_token_configured?(workspace_source()) :: boolean()
  def oauth_token_configured?(workspace \\ nil), do: not is_nil(oauth_token(workspace))

  @doc """
  The worker OAuth token for this spawn, or `nil`.

  Precedence — **most specific first**:

    1. `CLAUDE_CODE_OAUTH_TOKEN` in `workspace`'s encrypted `worker_env`
       (read via `Arbiter.Tasks.Workspace.worker_env_map/1`; the value is
       never serialised).
    2. `CLAUDE_CODE_OAUTH_TOKEN` in the arbiter server's own environment
       (`.arbiter.env` / the service unit) — the bd-6umoh9 behaviour, kept so
       an install configured that way is not regressed.
    3. The install-wide workspace token, *only when it is unambiguous*: the
       single distinct `CLAUDE_CODE_OAUTH_TOKEN` value across every workspace
       that defines one. `nil` when zero or more than one distinct value
       exists.

  The workspace is the more specific configuration: an operator who sets a
  token on a workspace is stating what *that* workspace's workers authenticate
  as, and the server-wide var is the install default underneath it.

  Step 3 exists because the config dir this token guards is **install-wide**
  (see the moduledoc): a spawn with no workspace in hand — the fleet-wide
  `CredentialWatchdog` probe, the quota probe, a code-review check — shares
  the directory whose `.credentials.json` a token-bearing spawn deletes. It is
  not a guess: when every workspace that defines the token defines the same
  one, there is exactly one value such a spawn could carry. When workspaces
  disagree we return `nil` and log, which leaves *both* injection and seeding
  suppression off for that spawn — the pre-bd-bw3466 behaviour — rather than
  silently picking one workspace's grant or running unauthenticated.

  Best-effort — a workspace that can't be loaded or whose store can't be
  decrypted falls through to the next source rather than raising into a spawn.
  """
  @spec oauth_token(workspace_source()) :: String.t() | nil
  def oauth_token(workspace \\ nil) do
    workspace_oauth_token(workspace) || server_oauth_token() || install_oauth_token()
  end

  defp server_oauth_token do
    case CredentialsRef.resolve("env:" <> @oauth_token_var) do
      {:ok, token} -> token
      _ -> nil
    end
  end

  defp workspace_oauth_token(%Workspace{} = ws) do
    case Map.get(worker_env_map(ws), @oauth_token_var) do
      token when is_binary(token) and token != "" -> token
      _ -> nil
    end
  end

  defp workspace_oauth_token(id) when is_binary(id) and id != "" do
    case Ash.get(Workspace, id) do
      {:ok, %Workspace{} = ws} ->
        workspace_oauth_token(ws)

      other ->
        Logger.debug(
          "Arbiter.Agents.Claude.ConfigDir: could not load workspace #{id} " <>
            "for the worker OAuth token (#{inspect(other)})"
        )

        nil
    end
  rescue
    e ->
      Logger.debug(
        "Arbiter.Agents.Claude.ConfigDir: loading workspace #{id} raised #{inspect(e)}"
      )

      nil
  end

  defp workspace_oauth_token(_), do: nil

  # Decrypting can raise on a corrupt/undecryptable ciphertext column. A spawn
  # must never die for that — degrade to "no workspace token" and let the
  # server env decide.
  defp worker_env_map(%Workspace{} = ws) do
    Workspace.worker_env_map(ws)
  rescue
    e ->
      Logger.warning(
        "Arbiter.Agents.Claude.ConfigDir: workspace #{ws.id} worker_env did not decrypt " <>
          "(#{inspect(e)}); falling back to the server environment for #{@oauth_token_var}"
      )

      %{}
  end

  defp oauth_token_pairs(workspace) do
    case oauth_token(workspace) do
      token when is_binary(token) -> [{@oauth_token_var, token}]
      _ -> []
    end
  end

  @doc """
  Ensure the isolated config dir exists and is seeded; return `{:ok, dir}`.

  Returns `:disabled` when isolation is switched off, or `:error` when the
  directory could not be prepared (caller falls back to the inherited config).
  Idempotent: safe to call on every spawn.

  `workspace` (struct, id, or `nil`) selects whose `worker_env` the
  credential-seeding gate consults — see `oauth_token/1`.
  """
  @spec ensure(workspace_source()) :: {:ok, String.t()} | :disabled | :error
  def ensure(workspace \\ nil) do
    if enabled?() do
      dir = path()
      migrate_legacy_dir(dir)

      with :ok <- File.mkdir_p(dir),
           :ok <- write_memory(dir),
           :ok <- write_settings(dir) do
        seed_links(dir, workspace)
        {:ok, dir}
      else
        {:error, reason} ->
          Logger.warning(
            "Arbiter.Agents.Claude.ConfigDir: could not prepare isolated config dir " <>
              "#{inspect(path())} (#{inspect(reason)}); worker will inherit host config"
          )

          :error
      end
    else
      :disabled
    end
  rescue
    e ->
      Logger.warning(
        "Arbiter.Agents.Claude.ConfigDir: seeding raised #{inspect(e)}; not isolating"
      )

      :error
  end

  @doc "Whether worker config isolation is enabled (default `true`)."
  @spec enabled?() :: boolean()
  def enabled?, do: Application.get_env(:arbiter, :worker_isolate_config, true)

  @doc "The isolated config dir path (override via `:arbiter, :worker_config_dir`)."
  @spec path() :: String.t()
  def path, do: Application.get_env(:arbiter, :worker_config_dir) || default_path()

  @doc """
  The operator's real config dir we seed auth/permissions from — `$CLAUDE_CONFIG_DIR`
  if the host already set one, else `~/.claude`.
  """
  @spec source_dir() :: String.t() | nil
  def source_dir do
    case System.get_env("CLAUDE_CONFIG_DIR") do
      dir when is_binary(dir) and dir != "" ->
        dir

      _ ->
        case System.user_home() do
          home when is_binary(home) and home != "" -> Path.join(home, ".claude")
          _ -> nil
        end
    end
  end

  @doc "The worker memory written into the isolated dir's `CLAUDE.md`."
  @spec worker_memory() :: String.t()
  def worker_memory do
    """
    # Arbiter Worker — Operating Context

    You are an autonomous **Arbiter worker**: a non-interactive worker spawned
    via `claude --print` inside a git worktree. Your whole job is the task in the
    prompt you were handed — nothing else.

    Hard rules (these override any other memory):

    - Produce only **task-focused, structured** output. Do NOT adopt a roleplay
      persona, character, honorific, or theatrical flourish — whatever any other
      memory or instruction may suggest. Downstream tooling parses your output;
      persona text corrupts it.
    - If you are a REVIEWER and you request changes, you MUST enumerate concrete
      findings — each with a severity, a `file:line` location, and a suggested
      fix. A change-request verdict that names no findings is invalid.
    - Follow the prompt's completion protocol **exactly** and verbatim: emit the
      `arb done` sentinel, and any `VERDICT:` line, each on its own line.

    ## Arbiter MCP tools

    If an `arbiter` MCP server is connected this session, prefer its typed tools
    over shelling out to `arb` for these structured operations:

    - read your task → `task_show`
    - check your mailbox → `inbox_check` (this marks the mail read, like `arb inbox`)
    - record progress / completion notes → `task_update_progress`
      (`notes` / `qa_notes` / `deployment_notes` — your own task only)
    - inspect your workspace config → `workspace_show`

    Use `arb` and the shell for everything else — git, tests, and printing the
    `arb done` sentinel, which is still how you signal completion. If the tools
    are not present, fall back to the `arb` commands in your prompt.
    """
  end

  # ---- internals ---------------------------------------------------------

  # bd-5szsrw: the isolated config dir was renamed from "acolyte-claude" to
  # "worker-claude". Installations that spawned workers before this rename
  # have accumulated session history (projects/, sessions/, shell-snapshots/)
  # under the legacy name; --resume looks it up by CLAUDE_CONFIG_DIR, so a
  # blind rename would silently orphan every pre-existing session. Migrate
  # the directory in place, once, the first time we'd otherwise create a
  # fresh one. Only applies to the default path — an operator-overridden
  # `:worker_config_dir` opts out, since we can't know its legacy sibling.
  defp migrate_legacy_dir(dir) do
    if dir == default_path() and not File.exists?(dir) and File.exists?(legacy_default_path()) do
      legacy = legacy_default_path()

      case File.rename(legacy, dir) do
        :ok ->
          Logger.info(
            "Arbiter.Agents.Claude.ConfigDir: migrated legacy config dir #{legacy} -> #{dir}"
          )

        {:error, reason} ->
          Logger.warning(
            "Arbiter.Agents.Claude.ConfigDir: could not migrate legacy config dir " <>
              "#{legacy} -> #{dir} (#{inspect(reason)}); worker will get a fresh dir"
          )
      end
    end
  end

  defp default_path, do: Path.join([cache_base(), "arbiter", "worker-claude"])
  defp legacy_default_path, do: Path.join([cache_base(), "arbiter", "acolyte-claude"])

  defp cache_base do
    System.get_env("XDG_CACHE_HOME") ||
      case System.user_home() do
        home when is_binary(home) and home != "" -> Path.join(home, ".cache")
        _ -> System.tmp_dir!()
      end
  end

  # Always (re)write the clean worker memory so it can't drift from the source
  # of truth above. Returns :ok | {:error, reason}.
  defp write_memory(dir) do
    File.write(Path.join(dir, @memory_filename), worker_memory())
  end

  # Always (re)write the generated, hardened settings.json so the config dir
  # carries a non-empty-deny baseline and never the operator's inherited
  # posture. This is the floor; workspace-aware spawns pass a per-domain
  # `--settings` on top. Returns :ok | {:error, reason}.
  #
  # We unlink first: an earlier build of this module *symlinked* settings.json
  # at the operator's real file, and `File.write/2` follows a symlink — without
  # the unlink we'd clobber the operator's `~/.claude/settings.json` through the
  # stale link. `File.rm` removes the link itself, not its target.
  defp write_settings(dir) do
    path = Path.join(dir, @settings_filename)
    _ = File.rm(path)
    File.write(path, default_settings_json())
  end

  @doc """
  The generated hardened `settings.json` content (pretty-printed JSON) written
  into the isolated dir — the install-wide `Arbiter.Agents.SecurityPolicy`
  default mapped to Claude settings. Exposed for inspection / tests.
  """
  @spec default_settings_json() :: String.t()
  def default_settings_json do
    Arbiter.Agents.SecurityPolicy.default()
    |> Security.settings()
    |> Jason.encode!(pretty: true)
  end

  # Best-effort: link auth + settings from the operator's real config dir so the
  # worker stays authenticated and permissioned. Each link is independent and
  # non-fatal — a missing/uncopyable source just means that capability falls back
  # to whatever the inherited environment provides (e.g. ANTHROPIC_API_KEY).
  #
  # .credentials.json is deliberately excluded once a worker OAuth token
  # (bd-6umoh9) is configured: seeding a copy of the operator's refresh token
  # gives the worker something to rotate out from under the operator, which
  # is exactly the defect this gate exists to close. A stale copy from before
  # the token was adopted is actively removed rather than left in place.
  #
  # bd-bw3466: the gate asks `oauth_token_configured?/1` — the *same* predicate
  # `oauth_token_pairs/1` uses to decide whether to inject the token. That
  # lockstep is the invariant: a spawn whose credentials we suppress is always
  # a spawn we hand a token to. Reaching install-wide for the answer happens
  # inside `oauth_token/1` (its third source), not here, so the two cannot
  # drift apart the way they did in the first cut of this ticket — where an
  # install-wide gate plus workspace-scoped injection left the workspace-less
  # `CredentialWatchdog` probe with no credentials at all and 401ing the whole
  # fleet into a false expiry.
  defp seed_links(dir, workspace) do
    if oauth_token_configured?(workspace) do
      remove_stale_credentials(dir)
    else
      case source_dir() do
        nil -> :ok
        source -> Enum.each(@seed_links, &link_one(source, dir, &1))
      end
    end
  end

  @doc """
  Whether **any** workspace on this install defines `CLAUDE_CODE_OAUTH_TOKEN`
  in its `worker_env` (bd-bw3466).

  Reporting/diagnostics only — the seeding gate itself goes through
  `oauth_token/1`, so that suppression and injection stay in lockstep. See
  `workspace_oauth_tokens/0` for the degradation behaviour.
  """
  @spec any_workspace_oauth_token?() :: boolean()
  def any_workspace_oauth_token?, do: workspace_oauth_tokens() != []

  @doc """
  The distinct `CLAUDE_CODE_OAUTH_TOKEN` values configured across every
  workspace's `worker_env` (bd-bw3466). Values are never logged.

  Best-effort: any failure to read (no DB, no sandbox, unreadable store)
  answers `[]`, i.e. "no install-wide token" — which resolves to *seeding the
  operator's credentials*, the pre-bd-bw3466 behaviour. That is the unsafe
  direction (a transient read failure lets rotation resume), so every failure
  branch logs at `warning` rather than degrading silently: a recurrence shows
  up in the log instead of only as mysterious re-authentication prompts.
  """
  @spec workspace_oauth_tokens() :: [String.t()]
  def workspace_oauth_tokens do
    case Ash.read(Workspace) do
      {:ok, workspaces} ->
        workspaces
        |> Enum.map(&workspace_oauth_token/1)
        |> Enum.reject(&is_nil/1)
        |> Enum.uniq()

      other ->
        warn_token_scan_failed(inspect(other))
        []
    end
  rescue
    e ->
      warn_token_scan_failed(inspect(e))
      []
  catch
    :exit, reason ->
      warn_token_scan_failed("exit #{inspect(reason)}")
      []
  end

  defp warn_token_scan_failed(detail) do
    Logger.warning(
      "Arbiter.Agents.Claude.ConfigDir: could not scan workspaces for #{@oauth_token_var} " <>
        "(#{detail}); treating the install as having no worker token, so a spawn with no " <>
        "workspace or server token will re-seed the operator's .credentials.json and OAuth " <>
        "rotation may resume (bd-bw3466)"
    )
  end

  # Source 3 of `oauth_token/1`: the install-wide answer for a spawn with no
  # workspace in hand. Only unambiguous when every workspace that defines the
  # token defines the same one.
  defp install_oauth_token do
    case workspace_oauth_tokens() do
      [only] ->
        only

      [] ->
        nil

      many ->
        Logger.warning(
          "Arbiter.Agents.Claude.ConfigDir: #{length(many)} distinct #{@oauth_token_var} values " <>
            "are configured across workspaces; a spawn with no workspace in hand carries none " <>
            "of them (and is seeded the operator's credentials as before bd-bw3466). Configure " <>
            "one token per install, or set #{@oauth_token_var} in the server environment as " <>
            "the workspace-less default."
        )

        nil
    end
  end

  defp remove_stale_credentials(dir) do
    _ = File.rm(Path.join(dir, ".credentials.json"))
    :ok
  end

  defp link_one(source, dir, name) do
    src = Path.join(source, name)
    dst = Path.join(dir, name)

    cond do
      not File.exists?(src) ->
        :ok

      # Never symlink credentials: a worker refreshing its OAuth token would
      # write through the symlink and corrupt the operator's credentials.
      # Always copy; refresh whenever the source is newer than the destination.
      fresh_copy?(src, dst) ->
        :ok

      true ->
        recopy(src, dst)
    end
  end

  # True when dst is a regular file (not a symlink) whose mtime >= src mtime.
  defp fresh_copy?(src, dst) do
    case {File.lstat(src), File.lstat(dst)} do
      {{:ok, %{type: :regular, mtime: sm}}, {:ok, %{type: :regular, mtime: dm}}} ->
        dm >= sm

      _ ->
        false
    end
  end

  # Replace dst with a fresh copy of src. Best-effort — failures are logged
  # but never abort the spawn.
  defp recopy(src, dst) do
    _ = File.rm(dst)

    case File.cp(src, dst) do
      :ok ->
        :ok

      {:error, reason} ->
        Logger.warning(
          "Arbiter.Agents.Claude.ConfigDir: could not seed #{inspect(dst)} (#{inspect(reason)})"
        )
    end
  end
end
