defmodule GtElixir.Repo.Migrations.AddDependencyResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:dependencies, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)

      add(
        :from_issue_id,
        references(:issues,
          column: :id,
          name: "dependencies_from_issue_id_fkey",
          type: :text,
          prefix: "public",
          on_delete: :restrict
        ), null: false)

      add(
        :to_issue_id,
        references(:issues,
          column: :id,
          name: "dependencies_to_issue_id_fkey",
          type: :text,
          prefix: "public",
          on_delete: :restrict
        ), null: false)

      add(:type, :text, null: false)
      add(:created_by, :text)
      add(:notes, :text, default: "")

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:dependencies, [:from_issue_id, :to_issue_id, :type],
        name: "dependencies_unique_edge_index"
      )
    )
  end

  def down do
    drop(constraint(:dependencies, "dependencies_from_issue_id_fkey"))

    drop(constraint(:dependencies, "dependencies_to_issue_id_fkey"))

    drop_if_exists(
      unique_index(:dependencies, [:from_issue_id, :to_issue_id, :type],
        name: "dependencies_unique_edge_index"
      )
    )

    drop(table(:dependencies))
  end
end
