defmodule ArbiterWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :arbiter_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_arbiter_web_key",
    signing_salt: "RokS/WOw",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :arbiter_web,
    gzip: not code_reloading?,
    only: ArbiterWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :arbiter_web
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # The Anthropic proxy (bd-5boun6) forwards raw request bodies verbatim to
  # api.anthropic.com, so it must NOT have its body parsed/consumed here. Every
  # other route parses as usual.
  @parsers_opts Plug.Parsers.init(
                  parsers: [:urlencoded, :multipart, :json],
                  pass: ["*/*"],
                  json_decoder: Phoenix.json_library()
                )

  plug :parse_except_proxy

  defp parse_except_proxy(%Plug.Conn{path_info: ["proxy" | _]} = conn, _opts), do: conn
  defp parse_except_proxy(conn, _opts), do: Plug.Parsers.call(conn, @parsers_opts)

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ArbiterWeb.Router
end
